<?php

/**
 *  Implements hook_menu().
 */
function testshelper_menu() {
  $items = array();

  $items['testshelper'] = array(
    'title' => 'Tests helper',
    'page callback' => 'testshelper_main_page',
    'file' => 'testshelper.pages.inc',
    'access callback' => TRUE,
  );

  $items['testshelper/pages-map'] = array(
    'title' => 'Tests helper - Pages map',
    'page callback' => 'testshelper_pagesmap_page',
    'file' => 'testshelper.pages.inc',
    'access callback' => TRUE,
  );

  $items['testshelper/rwd'] = array(
    'title' => 'Tests helper - RWD',
    'page callback' => 'testshelper_rwd_page',
    'file' => 'testshelper.rwd.pages.inc',
    'access callback' => TRUE,
  );

  return $items;
}