<?php
function homepage_permission() {
    return array(
        'manage homepage settings' => array(
            'title' => t('Manage homepage settings'),
        ),
    );
}


function homepage_menu() {
    return array(
        'kwest_homepage' => array(
            'title' => 'Homepage',
            'page callback' => 'theme',
            'page arguments' => array('kwest_homepage'),
            'access callback' => true,
            'type' => MENU_CALLBACK,
        ),
        'admin/config/kwest/homepage' => array(
            'title' => 'Homepage',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('homepage_admin_form'),
            'access arguments' => array('manage homepage settings'),
            'type' => MENU_NORMAL_ITEM,
        )
    );
}


function homepage_menu_alter(&$data) {
    unset($data['node']);
}


function homepage_admin_form() {
    $body = variable_get('kwest_homepage_body');
    $form = array(
        'kwest_homepage_header' => array(
            '#type' => 'textfield',
            '#title' => 'Header',
            '#default_value' => variable_get('kwest_homepage_header', 'Welcome'),
        ),
        'kwest_homepage_body' => array(
            '#type' => 'text_format',
            '#title' => 'Body',
            '#default_value' => isset($body['value']) ? $body['value'] : '',
        ),
        'kwest_homepage_background' => array(
            '#type' => 'managed_file',
            '#upload_location' => 'public://homepage/',
            '#title' => 'Background',
            '#default_value' => variable_get('kwest_homepage_background'),
        ),
    );
    $form = system_settings_form($form);
    $form['#submit'][] = 'homepage_admin_form_submit';
    return $form;
}


function homepage_admin_form_submit($form, &$form_state) {
    $file = file_load($form_state['values']['kwest_homepage_background']);
    $file->status = FILE_STATUS_PERMANENT;
    file_save($file);
    # Assign the image to admin user. It's a hack to prevent removal of "unused" images.
    file_usage_add($file, 'user', 'user', 1);
}


function homepage_theme() {
    return array(
        'kwest_homepage' => array(
            'variables' => array(),
            'template' => 'homepage',
        ),
    );
}
